#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 xxx" 1>&2
    exit 1
fi

if ! [[ "$1" =~ ^[1-9][0-9]{,2}$ ]]; then
    echo "Usage: $0 xxx (x=[0-9])" 1>&2
    exit 1
fi

if [ ! -e src ]; then
    echo "Error: directory 'src' not exists." 1>&2
    mkdir src
    echo "Directory 'src' has auto-generated by 'pesetup.sh'." 1>&2
fi

cp -n template/template.cpp src/$1.cpp

exit 0